#!/bin/sh

# Gradle startup script for POSIX generated by Gradle.

APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P)

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
}

fatal () {
    echo "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false

case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  MSYS* ) msys=true ;;
  * ) ;;
esac

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    if command -v gradle >/dev/null 2>&1; then
        exec gradle "$@"
    fi
    fatal "ERROR: gradle-wrapper.jar is missing and no 'gradle' command was found in PATH."
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        fatal "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$msys" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n "$MAX_FD" || warn "Could not set maximum file descriptor limit: $MAX_FD"
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules.
set --
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    $DEFAULT_JVM_OPTS \
    "-classpath" "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$APP_HOME" ]; then
    cd "$(dirname "$0")" || exit
fi

exec "$JAVACMD" "$@"
